### PR TITLE
[tcgc] allow scalar alternate types for unions, enums, and models

### LINKED ISSUE #3651: alternateType doesn't work on union type
[playground](https://azure.github.io/typespec-azure/playground/?options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fresource-manager%22%5D%7D%7D&c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3yvIK3Jlc291cmNlLW1hbmFnZXLfN2MtY2xpZW50LWdlbmVyYXRvcshtCnVzaW5nIEh0dHA7xwxSZXN0yAxW6QDEyBJBxF4uQ29yZc4SUucAkk3mAJHPL8V%2BR8h9xz8KLyoqIENvbnRvc2%2FEdsVAIFByb3ZpZGVyIOYA221lbnQgQVBJLiAqLwpAYXJtyCBOYW1lc3BhY2UKQHNlcnZpY2UoI3sgdGl0bGU6ICLHV8gtSHVi5gCEIiB9KQpA5wGbZWQo5wDhcykKbshQIE1pY3Jvc29mdC7SRu8AtkFQSSDHTXPkAKFlbnVt6AE1cyB7CiAgxC4yMDIxLTEwLTAxLXByZXZpZXfINcQ0ICDkANdDb21tb25U5AGwx0Ao9QFZLsspLshqLnY1KQogIGDSaWAsCn3mALNB6AC16wDOIOgCSOQAiG1vZGVsIEVtcGxveWVlIGlzIFRyYWNrZWToAII8yBxQcm9wZXJ0aWVzPuUA5C4u6QCm5AGWUGFyYW1ldGVyyTE%2BO%2BgAhslfcMlE0nzKYOkBQ0FnZSBvZiBlyD%2FlAThhZ2U%2FOiBpbnQzMjsKxylDaXR50ipjaXR5Pzogc3Ry5QLLxyxQcm9maWzTWUBlbmNvZGUoImJhc2U2NHVybCLkAWBwxjA%2FOiBieXRlc8lIVGhlIHN0YXR1c8RLdGhlIGxhc3Qg5ADFYXRpb27lArwgIEB2aXNpYmlsaXR5KExpZmVjeWNs5AHgYWTHXcQg5QNtU3RhdMRn5QGrzBTpAUjEc8wy5QCA5QDKYekB1cV3QGxyb8Q7dXMKdW7kAnLRVOUBZOYBGizsANLIRyBjcmXEJ3JlcXVlc3QgaGFzIGJlZW4gYWNjZXB0ZWTEZyAgQccOOiAiyAsi1lBpxEDkALTpAMHIROwAnDogIswP2kx1cGRhdMRPxUNVxw46ICLIC8o76QRl6QDE5gDcZOcBolN1Y2NlZWTlAMXJDNM%2FxTbkAU1mYWlsyT5GxQ06ICLGCdw4d2FzIGNhbmNlyj5Dxw%2FkBL3HC%2F8BQCBkZWxl6QGARMQN5gD5yAsi5QP9QGFsdGVybmF0ZeQENSgKICB1bmtub3duCinnAhNEZmU8VOYDy1QsxEthdGFGYWN0b3J5RWzlBYLESeYDpNIcxThraW7kALpFeHByZXPkAbMiOwogIHZhbHVl6gN38AQEbW926gJX6QQGTW92ZVLHFegD%2F%2BQBAG1vduQA9WZyb20gbG9j5gFJ5QD7xBPxA93LM3RvzzF0b%2F8AlXJlc3BvbnPrBRjmAJbHFuwAl%2B4D%2BcU%2BxWTGfOYDezrlAWPGcuYFDGludGVyZuQGbk%2FoBCZzIGV4dGVuZHP2B1Iuyyl75QHXcm3II8oby1noANLmBUVnZXTkAjlByjXkBHnsBaIg5wMNT3LlAznlAmjLL0PHHVJlcGxhY2VBc3luY84%2F5QOJyDdDdXN0b21QYXRjaFPEKgogICDpAJPkAmUg9wDnRm91buQDuOQG18gc5gCRTeQBiclzLPMGLz4KICDlAIvmAxrvAMLlAxdlV2l0aG91dE9r8wDCbGlzdEJ5yDBHcm91cM9ETMUiUGFyZW501DxTdWJzY3JpcOUCbMY7xjPMGcw56AbgIHNhbXBs6wPmYWPFRHRoYXTmAlbpBqN0byBkaWZmZeQAhO8C2cUp7gCyQcVI5QGEyHcs7ANkyA3mAtvzAJJIRUFE6gbMxH5jaGVja%2BoAqmV4aXN0ZW7mCEYgxh5FyRTvAkbNHe4IIQ%3D%3D&e=%40azure-tools%2Ftypespec-client-generator-core&vs=%7B%7D)

**Expected:** MoveResponse.movingStatus is `unknown`.
**Actual:** MoveResponse.movingStatus is still its original type.

### PR DESCRIPTION
**Pull request by iscai-msft**
fixes #3651

### CODE REVIEW

File: packages/typespec-client-generator-core/src/interfaces.ts [hunk 1]
```diff
@@ -1372,3 +1367,14 @@ export interface SdkModelExampleValue extends SdkExampleValueBase {
   value: Record<string, SdkExampleValue>;
   additionalPropertiesValue?: Record<string, SdkExampleValue>;
 }
+
+export function getScalarAlternateType(
```
Comment (tadelesh) [inline packages/typespec-client-generator-core/src/interfaces.ts]: I don't think we should put function in `interface.ts`. Could you move it to internal/public utils?

Comment (tadelesh) [reply packages/typespec-client-generator-core/src/interfaces.ts]: Also, I don't think the return will always be a `Scalar`.

File: packages/typespec-client-generator-core/src/types.ts [hunk 2]
```diff
@@ -1081,6 +1081,13 @@ export function getClientTypeWithDiagnostics(
       retval = diagnostics.pipe(getSdkTupleWithDiagnostics(context, type, operation));
       break;
     case "Model":
+      const scalarAlternateTypeForModel = getScalarAlternateType(context, type);
```
Comment (tadelesh) [inline packages/typespec-client-generator-core/src/types.ts]: Can we do the replacement in a single place instead of doing it separately?

File: packages/typespec-client-generator-core/src/interfaces.ts (hunk 1 above)
Comment (iscai-msft) [reply packages/typespec-client-generator-core/src/interfaces.ts]: oh meant to put it in internal-utils. thanks for the catch!
