### PR TITLE
[tcgc] fix clientNamespace bug when used earlier in namespace path

### LINKED ISSUE #2500: [Bug]: TCGC, clientNamespace on TypeSpec Namespace does not override "namespace" emitter option
### Describe the bug

In some cases, the `@clientNamespace` decorator on Namespace is not able to override `namespace` emitter options.

@iscai-msft 

### Reproduction

TCGC 0.54.0

Run Java emitter on
https://github.com/Azure/typespec-azure/blob/main/packages/azure-http-specs/specs/client/namespace/client.tsp
with `namespace=client.noeffect` emitter option

(note that below would not show up in generated code, as Java emitter is WIP switching behavior, when both option and decorator provided)

The client.tsp have `@clientNamespace` override on all TypeSpec Namespaces.
Here is the override `@@clientNamespace(FirstModel, "client.clientnamespace.first", "java");`

However, from TCGC output, the client namespace of `FirstClientResult` model (it is under `FirstModel` Namespace) is `client.noeffect`
Image

---

If `namespace=client.noeffect` emitter option is not provided, `@clientNamespace` works fine. Here is a screenshot
Image

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by iscai-msft**
fixes #2500

### CODE REVIEW

File: packages/typespec-client-generator-core/src/decorators.ts [hunk 1]
```diff
@@ -1207,43 +1207,47 @@ export function getClientNamespace(
   entity: Namespace | Interface | Model | Enum | Union,
 ): string {
   const override = getScopedDecoratorData(context, clientNamespaceKey, entity);
-  if (override) {
+  const { namespace, isOverriddenInNamespace } = getNamespaceFullNameWithOverride(context, entity);
+  if (override || isOverriddenInNamespace) {
+    const overriddenNamespace = override || namespace;
```
Comment (weidongxu-microsoft) [inline packages/typespec-client-generator-core/src/decorators.ts:1212]: I think the idea is correct, that it checks whether the model is contained in a Namespace that has `@clientNamespace`.

I am not sure whether the response of `namespace` var is correct. For
```ts
@clientNamespace("client.namespace")
namespace Client {
  namespace Sub {
    model Model {
       ...
    }
  }
}
```
It seems the func would return `client.namespace.Sub` as namespace for `Model`?

I am unsure whether `Sub` should be included in the result. (I guess this may be an ambiguity from the design)

Other than this ambiguity, PR looks good.

**Review by weidongxu-microsoft — APPROVED** [review]

File: packages/typespec-client-generator-core/src/decorators.ts (hunk 1 above)
Comment (iscai-msft) [reply packages/typespec-client-generator-core/src/decorators.ts]: we should generate it as `client.namesapce.Sub` I believe, i still think client namesapce should not flatten everything within its namespace
