### PR TITLE
fix(tcgc): set sdk method body parameter encode with http content type

### LINKED ISSUE #1084: [Bug][TCGC]: inconsistent `encode` between SdkMethodParameter and HttpOperationParameter
### Describe the bug

Check this spec: https://github.com/Azure/autorest.csharp/blob/6d5884d0b9b1367f5d36ab648aecab41baccf33b/test/TestProjects/MediaTypes-TypeSpec/MediaTypes-TypeSpec.tsp#L29

The request body is defined as `bytes`.

Parsing the spec, and check the type of both `SdkMethodParameter` and `HttpOperationParamter`, you'll find their `encode` is different. The one in `SdkMethodParameter` is correct (e.g. `base64`).

### SdkMethodParameter
image

### HttpOperationParameter
image

### Reproduction

Just try to parse the definition above.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by archerzz**
- after fetching the sdk method body parameter, reset its encode according to the underlying http request content-type
- add unit test

fix #1084

### CODE REVIEW

File: packages/typespec-client-generator-core/src/package.ts [hunk 1]
```diff
@@ -247,6 +248,19 @@ function getSdkBasicServiceMethod<TServiceOperation extends SdkServiceOperation>
   const serviceOperation = diagnostics.pipe(
     getSdkServiceOperation<TServiceOperation>(context, operation, methodParameters)
   );
+  // set the correct encode for body parameter according to the content-type
```
Comment (archerzz) [inline packages/typespec-client-generator-core/src/package.ts:251]: Another way to set the `encode` is trying to get the http parameter type encode value. That's quite ugly because you have to do a lot of type detection since here we only have `SdkType`.

**Review by iscai-msft — APPROVED** [review]
