### PR TITLE
[tcgc] unify datetime casing by renaming interface types

### LINKED ISSUE #799: [Bug]: Typo in `SdkDatetimeType`
### Describe the bug

Spell check will flag this word `Datetime`, but it should be `DateTime`.
There are inconsistencies among TCGC:
https://github.com/Azure/typespec-azure/blob/be1e2c332a991ed935dcd51db40bdefc7f83d86e/packages/typespec-client-generator-core/src/interfaces.ts#L222
https://github.com/Azure/typespec-azure/blob/be1e2c332a991ed935dcd51db40bdefc7f83d86e/packages/typespec-client-generator-core/src/interfaces.ts#L215
https://github.com/Azure/typespec-azure/blob/be1e2c332a991ed935dcd51db40bdefc7f83d86e/packages/typespec-client-generator-core/src/interfaces.ts#L219

### Reproduction

Just check the code:
https://github.com/Azure/typespec-azure/blob/be1e2c332a991ed935dcd51db40bdefc7f83d86e/packages/typespec-client-generator-core/src/interfaces.ts#L222
https://github.com/Azure/typespec-azure/blob/be1e2c332a991ed935dcd51db40bdefc7f83d86e/packages/typespec-client-generator-core/src/interfaces.ts#L215
https://github.com/Azure/typespec-azure/blob/be1e2c332a991ed935dcd51db40bdefc7f83d86e/packages/typespec-client-generator-core/src/interfaces.ts#L219

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by iscai-msft**
fixes #799

### CODE REVIEW

File: packages/typespec-client-generator-core/src/interfaces.ts [hunk 1]
```diff
@@ -86,7 +86,7 @@ interface SdkTypeBase {
 
 export type SdkType =
   | SdkBuiltInType
-  | SdkDatetimeType
+  | SdkDateTimeType
```
Comment (srnagar) [inline packages/typespec-client-generator-core/src/interfaces.ts:89]: This is a breaking change as we use this type in [our emitter ](https://github.com/Azure/autorest.java/blob/main/typespec-extension/src/code-model-builder.ts#L51)

**Review by srnagar — APPROVED** [review]
LGTM
